name: Test

on:
  workflow_dispatch:

jobs:
  request:
    runs-on: ubuntu-latest
    name: Run echo tests
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Request Postment Echo POST
        uses: ./
        with:
          url: "https://webhook.site/50adeabb-8e38-402a-9ad7-f08373fd953e"
          hmacSecret: '9aa66a8c37255ae2b71d82b1e4bffdb1'
          data: '{ "key": "value" }'
